name = "threatanalyzer-api"
main = "worker.js"
compatibility_date = "2024-01-01"

workers_dev = true

# routes = [
#   { pattern = "threatanalyzer-api.juanlunadevelop.workers.dev", zone_name = "juanlunadevelop.workers.dev" }
# ]

[vars]
ENVIRONMENT = "production"
